# Generated by Django 2.1.5 on 2019-01-09 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('product_measurement', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('pickup_details', models.CharField(max_length=200)),
                ('pickup_starttime', models.DateTimeField(verbose_name='pickup_starttime')),
                ('pickup_endtime', models.DateTimeField(verbose_name='pickup_endtime')),
                ('donee', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
