# Generated by Django 2.1.5 on 2019-01-09 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
