# Generated by Django 2.1.5 on 2019-01-09 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190109_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='donee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_address2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
