# Generated by Django 2.1.5 on 2019-01-15 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190113_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donee', to=settings.AUTH_USER_MODEL),
        ),
    ]
